// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbpJe4c_McSoXI3VK9J8bw8PuYphSz0ig',
    appId: '1:17686223363:ios:ed933a9c929a156f52cc36',
    messagingSenderId: '17686223363',
    projectId: 'campus-date-v2-33efa',
    storageBucket: 'campus-date-v2-33efa.firebasestorage.app',
    iosBundleId: 'com.example.campusDatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ4RyI6PBAWRxlI4gfO0ySAdunrBqk3ac',
    appId: '1:17686223363:web:cc78186ec044a11d52cc36',
    messagingSenderId: '17686223363',
    projectId: 'campus-date-v2-33efa',
    authDomain: 'campus-date-v2-33efa.firebaseapp.com',
    storageBucket: 'campus-date-v2-33efa.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4RyI6PBAWRxlI4gfO0ySAdunrBqk3ac',
    appId: '1:17686223363:web:25e4b4c981c0f4a752cc36',
    messagingSenderId: '17686223363',
    projectId: 'campus-date-v2-33efa',
    authDomain: 'campus-date-v2-33efa.firebaseapp.com',
    storageBucket: 'campus-date-v2-33efa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbpJe4c_McSoXI3VK9J8bw8PuYphSz0ig',
    appId: '1:17686223363:ios:ed933a9c929a156f52cc36',
    messagingSenderId: '17686223363',
    projectId: 'campus-date-v2-33efa',
    storageBucket: 'campus-date-v2-33efa.firebasestorage.app',
    iosBundleId: 'com.example.campusDatingApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhOBIiGAjIZutvn7NzsfF97gRp33fbRy0',
    appId: '1:17686223363:android:84dc446ff45baa2e52cc36',
    messagingSenderId: '17686223363',
    projectId: 'campus-date-v2-33efa',
    storageBucket: 'campus-date-v2-33efa.firebasestorage.app',
  );

}